# Minimal Hyprland config

monitor=,preferred,auto,auto

input {
  kb_layout = us
}

# Set mod key
#$mod = SUPER
$mod = ALT

bind = $mod SHIFT, R, exec, hyprctl reload

# ── Apps ──
bind = $mod, Return, exec, alacritty
bind = $mod, Space, exec, wofi --show drun
bind = $mod, B, exec, brave

# ── Exit ──
bind = $mod, Q, killactive
bind = $mod SHIFT, Q, exit

# ── Focus ──
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

# ── Workspaces ──
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

exec-once = hyprctl dispatch workspace 2
