# Minimal Hyprland config

monitor=,preferred,auto,auto

input {
  kb_layout = us
}

# Set mod key
#$mod = SUPER
$mod = ALT

bind = $mod SHIFT, R, exec, hyprctl reload

# ── Apps ──
bind = $mod, Return, exec, alacritty
bind = $mod, Space, exec, wofi --show drun
bind = $mod, B, exec, brave

# ── Exit ──
bind = $mod, Q, killactive
bind = $mod SHIFT, Q, exit

# ── Focus ──
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

# ── Workspaces ──
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# Reboot
bind = $mod SHIFT, R, exec, systemctl reboot

# Shutdown
bind = $mod SHIFT, S, exec, systemctl poweroff

# Media key volume control
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t

# ── Initialisation ──

windowrulev2 = workspace 1, class:(brave-browser)
windowrulev2 = workspace 2, class:(Alacritty)

exec-once = alacritty -e sh -c "tmux new-session -d -s 0 -n win -c ~/dotfiles-nix/; tmux send-keys -t 0:win 'sh \$HOME/.tmux_init_actions.sh' Enter; tmux attach -t 0:win"
exec-once = brave
exec-once = udiskie --no-tray --notify &
exec-once = hyprctl dispatch workspace 1
