# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

stream: false                     # Controls whether to use the stream-style API.
save: true                       # Indicates whether to persist the message
keybindings: vi               # Choose keybinding style (emacs, vi)
editor: nvim                     # Specifies the command used to edit input buffer or session. (e.g. vim, emacs, nano).
wrap: no                         # Controls text wrapping (no, auto, <max-width>)
wrap_code: false                 # Enables or disables wrapping of code blocks

model: openai:gpt-5-mini
# https://github.com/sigoden/aichat/wiki/Environment-Variables
